#
# Jonathan Cormier Ticker YAML
#
show-tags: true
show-fundamentals: true
show-separator: true
# show-summary: true
interval: 5
currency: symbol
# sort: alpha 

watchlist:
  - ^GSPC
  - PLTR
  - DTEA
  - BEP-UN.TO
  - BEPC.TO
  - BAM-A.TO
  - CCO.TO
  - MSFT
  - MMED.NE
  - DIR-UN
  - D-UN
  - TFII.TO
  - CMPS
  - BRAX.CN
  - CURA.CN
  - CG.TO
  - NUMI.V
  - BNS.TO
  - WRN.TO
  - ATZ.TO
  - AQN.TO
  - CYBN.NE
  - ATAI
  - FTRP.TO
  - CRSP
  - TRIP.CN

#colors:
#  text: "#005fff"
#  text-light: "#0087ff"
#  text-label: "#00d7ff"
#  text-line: "#00ffff"
#  text-tag: "#005fff"
#  background-tag: "#0087ff"
