#
# Jonathan Cormier Ticker YAML
#
show-tags: true
show-fundamentals: true
show-separator: true
# show-summary: true
interval: 5
currency: symbol
# sort: alpha 

watchlist:
  - ^GSPC
  - PLTR
  - BEP-UN.TO
  - BEPC.TO
  - BAM-A.TO
  - CCO.TO
  - MSFT
  - DIR-UN
  - D-UN
  - TFII.TO
  - BNS.TO
  - WRN.TO
  - CS.TO
  - ATZ.TO
  - AQN.TO
  - HWKN
  - EVGO
  - NVDA

#colors:
#  text: "#005fff"
#  text-light: "#0087ff"
#  text-label: "#00d7ff"
#  text-line: "#00ffff"
#  text-tag: "#005fff"
#  background-tag: "#0087ff"
