#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Jonathan Cormier"
email = "jonathan@cormier.co"

[ui]
editor = "nvim"
default-command = ["log", "--reversed"]
show-cryptographic-signatures = true
pager = "delta"
merge-editor = "nvim3"
diff-editor = ":builtin"

[merge-tools.nvim3]
program = "nvim"
merge-args = ["-d", "$left", "$base", "$right", "$output"]

[signing]
behavior = "own"
backend = "gpg"
sign-all = true
key = "34CD09BD8A253BB518746C3E3C15099390069BAF"

[git]
sign-on-push = true

[aliases]
ai-describe = ["util", "exec", "--", "bash", "-c", """
  rev="${1:-@}"
  jj diff -r "$rev" | claude -p 'Write a concise commit message for these changes in the conventional commits format' | jj describe -r "$rev" --stdin --editor
""", "--"]
track-remote = ["util", "exec", "--", "bash", "-c", """
  pattern="${1:-.}"
  jj bookmark list --all-remotes | grep -E "$pattern" | grep '@' | awk '{print $1}' | xargs -I{} jj bookmark track {}
""", "--"]

[revset-aliases]
"wip" = "description(exact:'') & mine()"
"stacked" = "ancestors(@, 5) ~ immutable_heads()"

[template-aliases]
'format_short_cryptographic_signature(sig)' = '''
if(sig,
  if(sig.status() == "good", "🔒",
    if(sig.status() == "unknown", "❓",
      if(sig.status() == "bad", "💀",
        sig.status()
      )
    )
  ),
  "🚫",
)
'''

[templates]
log = "builtin_log_oneline"
